### ISSUE TITLE
Provide patches for modified binaries

### ISSUE THREAD

**Issue by x1nixmzeng** [ShootMe/CelesteTAS#2]
One suggestion for modifying the game without distributing binaries would be to provide patches using something like [Lame Patcher](http://aluigi.altervista.org/mytoolz.htm#lpatch).

It generates a binary diff file with MD5 checks for different versions, etc.

**Comment by ShootMe** [comment]
Doing that is also a bit of work, and still requires the person trying to use it knows how to patch everything correctly. If you want to provide the patch files, Ill upload them to the release, but I don't plan to support it for now.
