### ISSUE TITLE
Suggestion: document how to disable stat tracking

### ISSUE THREAD

**Issue by BenLubar** [ShootMe/CelesteTAS#3]
I don't want to poison my achievements and stats from running or recording a TAS, so I made the following changes:

Celeste.Achievements.Register: replace if statement condition:
```
public static void Register(Achievement achievement)
{
	if (Achievements.Has(achievement) || TAS.Manager.Recording || TAS.Manager.Running)
	{
```

Celeste.Stats.Increment: replace if statement condition:
```
public static void Increment(Stat stat, int increment = 1)
{
	if (Stats.ready && !TAS.Manager.Recording && !TAS.Manager.Running)
	{
```

**Comment by ShootMe** [comment]
Added info to the WhatsModified.txt document
