### ISSUE TITLE
Error when trying to run the Celeste Interlop Mod

### ISSUE THREAD

**Issue by mgclark007** [ShootMe/CelesteTAS#38]
Before I detail my issue, here is the instructions on the main page for reference.
-----

Everest
The easiest way to install is through the Everest interop mod.

1. Download the zip from here
2. Place it in your Mods directory (The .zip itself, not the contents)
3. Download the TAS addon here, either Celeste-Addons-OpenGL.dll or Celeste-Addons-XNA.dll, whichever corresponds with your version of Celeste
a. If you're unsure of your version, Steam defaults to XNA and Epic Games always is OpenGL
4. Place it in the same directory as Celeste.exe
5. Enable TAS in the mod settings.
------

Those were the instructions (for reference). I followed an iamdadbod video on how to download Everest (lastest version: 1051) to get my Mods folder and all the files, then downloaded the Everest Interlop Mod from Step 1 (called CelesteTAS-EverestInterlop.zip)

I placed the .zip file into the Mods directory.

I then downloaded the TAS addon from Step 3 (I run steam so I downloaded the -XNA.dll version) and placed it into my Celeste directory with Celeste.exe

Now here's where the problem starts. I boot Celeste and get this nasty error in the error_log.txt file:

`Ver 1.3.1.2 [Everest: 1051-azure-1a31c]
10/06/2019 22:32:57
System.TypeLoadException: Could not load type 'MonoMod.RuntimeDetour.HookGen.ILManipulator' from assembly 'MonoMod.RuntimeDetour, Version=19.9.1.6, Culture=neutral, PublicKeyToken=null'.
   at TAS.EverestInterop.CelesteTASModule.Load()
   at Celeste.Mod.Everest.Register(EverestModule module) in d:\a\1\s\Celeste.Mod.mm\Mod\Everest\Everest.cs:line 439
   at Celeste.Mod.Everest.Loader.LoadModAssembly(EverestModuleMetadata meta, Assembly asm) in d:\a\1\s\Celeste.Mod.mm\Mod\Everest\Everest.Loader.cs:line 431
   at Celeste.Mod.Everest.Loader.LoadMod(EverestModuleMetadata meta) in d:\a\1\s\Celeste.Mod.mm\Mod\Everest\Everest.Loader.cs:line 359
   at Celeste.Mod.Everest.Loader.LoadModDelayed(EverestModuleMetadata meta, Action callback) in d:\a\1\s\Celeste.Mod.mm\Mod\Everest\Everest.Loader.cs:line 319
   at Celeste.Mod.Everest.Loader.LoadZip(String archive) in d:\a\1\s\Celeste.Mod.mm\Mod\Everest\Everest.Loader.cs:line 0
   at Celeste.Mod.Everest.Loader.LoadAuto() in d:\a\1\s\Celeste.Mod.mm\Mod\Everest\Everest.Loader.cs:line 78
   at Celeste.Mod.Everest.Boot() in d:\a\1\s\Celeste.Mod.mm\Mod\Everest\Everest.cs:line 233
   at Celeste.Celeste..ctor() in d:\a\1\s\Celeste.Mod.mm\Patches\Celeste.cs:line 186
   at Celeste.Celeste.orig_Main(String[] args)`

-----
In an attempt to debug the error, I removed the CelesteTAS-EverestInterlop.zip file from my Mods directory, and the game booted just fine.

I have two hypotheses as to why the installation didn't work.

Hypothesis 1. I did not complete Step 5 of the Installation directions. Step 5 says to "enable TAS in the mod settings."
I do not know what this means, nor how to complete it. I checked the "mod options" menu option from the Celeste game. I also looked at all the Celeste.Mod.mm files with Notepad++ to see if there was a "TAS" option for me to enable. Alas, I do not know how these files work and do not want to edit them for fear of creating new problems.

I could not find any folder, nor file that indicated anything about "Mod Settings" nor a place for me to change enable an option for "TAS."

Hypothesis 2. There is a bug within the CelesteTAS-EverlestInterlop.zip file.
As of this report, the latest commit to the CelesteTAS github was 10 hours ago. To me, this means that there perhaps might have been a bug in the newest commit. However, I'm not one to judge this - I didn't write any of the code.

-----
Following this report (which I hope I detailed sufficiently) I have two requests:

1. How do I follow the Instructions Step 5 to "Enable TAS in the Mod Settings"?
2. Are there any bugs in the recent commit which could be causing my error?

To finish this report, I would like to thank you for creating this tool! I wouldn't have the opportunity to begin TAS-ing Celeste otherwise. I truly appreciate any reply to this post and hope that I will be able to fix my errors!

**Comment by ShootMe** [comment]
I would join the discord (https://discord.gg/AnrP74B) if you haven't already. I don't have any experience with setting up the TAS with Everest as I've never used it. You should be able to get help with it in the TAS or modding channels though.
