### ISSUE TITLE
4SHC after collect the disk

### ISSUE THREAD

**Issue by MeGaNeKoS** [ShootMe/CelesteTAS#49]
there's unsync command in #lvl_a-11 in 4shc file. i'm using the lastest celeste from steam.
sorry cant describe the problem but i cant progress future after collecting the tape/disk

**Comment by ShootMe** [comment]
These inputs are old as stated in the Readme.

Current ones afaik
https://github.com/EuniverseCat/CelesteTAS/tree/master/LevelFiles
