### ISSUE TITLE
Error when replacing the body of the method in Update(GameTime).

### ISSUE THREAD

**Issue by Drawleks** [ShootMe/CelesteTAS#7]
Hi, the description error is "The type or namespace name 'FinalBoss' could not be found (are you missing a using directive or an assembly reference?)
I couldn't find anything on the web if u could help it would be nice !
Thank you.

**Comment by ShootMe** [comment]
Make sure you are using the latest version of dnSpy. FinalBoss is a class within Celeste so it should find it if you are modifying things correctly.
