### ISSUE TITLE
Error when launching

### ISSUE THREAD

**Issue by SkyToast** [ShootMe/CelesteTAS#8]
I'm almost positive I've been following the steps right because I tried multiple times, but whenever I try to launch the modified Celeste application, it gives me an error says that I am missing celeste.autosplitterinfo.

Is that a seperate download, or did I mess up the code somewhere?

**Comment by ShootMe** [comment]
I have no clue why you would get that error, the TAS code doesn't reference it. I imagine something is not going correctly. If you want more help with it I suggest joining the discord https://discord.gg/VVKffPS and messaging me (DevilSquirrel) or KDT.
